Repository XenitAB/azure-devops-templates, pull requests merged in 2020-10, with the labels that each got.

#6 Add gitops docs
  assets/diagram.drawio
  assets/gitops-architecture.jpg
  gitops/README.md
Labels: documentation

#17 Pull with rebase before pushing
  gitops/deploy/deploy.yaml
Labels: hacktoberfest-accepted

#19 Add image scan
  gitops/README.md
  gitops/build/main.yaml
Labels: hacktoberfest-accepted

#27 Pr trigger
  gitops/README.md
  gitops/build/main.yaml
Labels: enhancement, hacktoberfest-accepted
